### PR TITLE
Change sample server sources to use English throughout

### PR DESCRIPTION
**Pull request by dthaler**
Previously it was a mix of English and German, with many typos in
English.

Signed-off-by: Dave Thaler <dthaler@microsoft.com>

### CODE REVIEW

**Comment by bernd-edlinger** [comment]
Please rebase and squash the 3 commits into one.

**Comment by dthaler** [comment]
rebased and squashed

**Comment by bernd-edlinger** [comment]
Dave, could you please fix this?

```
browseservice.c: In function ‘browse’:
browseservice.c:326:76: error: ‘_my_continuationpoint_ {aka struct <anonymous>}’ has no member named ‘Cont_Point_Identiefer’
               ((_my_continuationpoint_*)a_pResults->ContinuationPoint.Data)->Cont_Point_Identiefer=Cont_Point_Counter;
                                                                            ^

```

**Comment by dthaler** [comment]
Done

**Pull request merged**
