### PR TITLE
missing handling for OPCUA_P_NATIVE64 == 0

### PR DESCRIPTION
**Pull request by MarkusErlmann**

### CODE REVIEW

**Comment by bernd-edlinger** [comment]
But even with this patch the stack still does not build.

The stack is mostly C90 however "long long" is C99,
also other parts in the stack use C99 features,
for instance variadic macros.

I always considered OPCUA_P_NATIVE64=0 a thing of the past.

**Comment by MarkusErlmann** [comment]
@bernd-edlinger As I wrote in #68: 

>The majority of the issues needs to be solved in the platform layers, however some work has to be done in the platform independent part.

In order to be able to compile on `Win32`, additional modifications need to be done in the `Win32` platform layer. However, we're not using the `Win32` platform layer and fixed the remaining issues in our platform layer.

And there **are** still platforms that simply don't have native 64 bit data types.

**Comment by bernd-edlinger** [comment]
So I am unable to test (or support) this configuration.
However I see the macro OpcUa_UInt64_Initialize cast a `OpcUa_UInt64*` to a `OpcUa_Int64*`,
which violates the C language's strict aliasing rules.

**Comment by bernd-edlinger** [comment]
> And there are still platforms that simply don't have native 64 bit data types.

interesting, but I really wonder how OpenSSL will work without 64 bit integers,
for instance see `crypto/sha/sha512.c`:

```
 * Caveat lector.
 *
 * Implementation relies on the fact that "long long" is 64-bit on
 * both 32- and 64-bit platforms. If some compiler vendor comes up
 * with 128-bit long long, adjustment to sha.h would be required.
 * As this implementation relies on 64-bit integer type, it's totally
 * inappropriate for platforms which don't support it, most notably
 * 16-bit platforms.
```

**Pull request closed without merging**
