### PR TITLE
Change build system to CMake

### PR DESCRIPTION
**Pull request by paroga**

### CODE REVIEW

**Comment by JorisSpekreijse** [comment]
Instead of replacing, it would be better to add it.
Why remove the Visual Studio project files?

**Comment by paroga** [comment]
Do you think that maintaining more than one build system is a good idea? The idea behind CMake is, that we only have to make changes in one file.

**Comment by JorisSpekreijse** [comment]
CMake is a good idea.
But let the owners decide how many tools, projects, etc. they want to maintain. Now it is too assertive by adding your idea and make them force to remove something.

**Comment by cpipero** [comment]
I second the CMake porting option for an ANSI C project.

**Comment by marcschier** [comment]
I just submitted a PR with pretty much the same changes.  Then I realized that this one has the same feature but already has been around for almost a year (could have saved me some time :-)).  Anyway, I agree with not removing the original tool chain, which I have not done.  Since this PR is old I will take a fresh run at it.  But I would not want to steal anyone's thunder, so if there is interest I can merge my changes into this one.

**Comment by bernd-edlinger** [comment]
Closing, as the other PR was merged.
Thanks.

**Pull request closed without merging**
